%YAML 1.2
---
!VarNamePersist
Data: 
  IDictionary.Entries: 
    NumBuoys: 
      Value: !System.Single 1
      DisplayText: Количество буев
    GreenZoneD: 
      Value: !System.Single 1000
      DisplayText: Диаметр зеленой зоны
    MPC_RANGE: 
      Value: !System.Single 10
      DisplayText: Дальность обнаружения МПЦ
    BuoysDetectRange: 
      Value: !System.Single 5000
      DisplayText: Дальность обнаружения буями
    BuoyReadyTime: 
      Value: !System.Single 3
      DisplayText: Время готовности буя
    MPC_DISTANCE: 
      Value: !System.Single 800
      DisplayText: Дистанция МПЦ
    RocketNum: 
      Value: !System.Single 4
      DisplayText: Количество ракет
    BuoyBreakStartAltitude: 
      Value: !System.Single 50
      DisplayText: Высота начала торможения буя
    StartBearingToTarget: 
      Value: !System.Single 180
      DisplayText: КУ цели
    BuoysShootRangeDiff: 
      Value: !System.Single 1000
      DisplayText: Разность дальности полета буев
    Weather: 
      Value: !System.Single 0
      DisplayText: Погода
    RocketPauseDuration: 
      Value: !System.Single 3
      DisplayText: Временной сдвиг пуска ракет
    RocketDistance: 
      Value: !System.Single 100
      DisplayText: Расстояние между ракетами при ударе
    BuoysShootRange: 
      Value: !System.Single 5000
      DisplayText: Дальность полета буев
    BuoysDistanceBetween: 
      Value: !System.Single 1000
      DisplayText: Расстояние между буями
    StartDistanceToTarget: 
      Value: !System.Single 7000
      DisplayText: Расстояние до цели
    YellowZoneD: 
      Value: !System.Single 1500
      DisplayText: Диаметр желтой зоны
    RocketDestroyRadius: 
      Value: !System.Single 500
      DisplayText: Радиус поражения ракет
    BuoysBearingMultplier: 
      Value: !System.Single 2
      DisplayText: Множитель погрешности обнаружения буя при шторме
    BuoysBearingError: 
      Value: !System.Single 5
      DisplayText: Погрешность пеленга буя
...
