%YAML 1.2
---
!VarNamePersist
Data: 
  IDictionary.Entries: 
    BuoysBearingMultplier: 
      Value: !System.Single 2
      DisplayText: Множитель погрешности обнаружения буя при шторме
    StartBearingToTarget: 
      Value: !System.Single 180
      DisplayText: КУ Цели
    GreenZoneD: 
      Value: !System.Single 500
      DisplayText: Диаметр зеленой зоны
    YellowZoneD: 
      Value: !System.Single 900
      DisplayText: Диаметр желтой зоны
    BuoysBearingError: 
      Value: !System.Single 5
      DisplayText: Погрешность пеленга буя
    RocketPauseDuration: 
      Value: !System.Single 3
      DisplayText: Временной сдвиг пуска ракет
    MPC_DISTANCE: 
      Value: !System.Single 800
      DisplayText: Дистанция МПЦ
    BuoyReadyTime: 
      Value: !System.Single 3
      DisplayText: Время готовности буя
    BouysDistanceBetween: 
      Value: !System.Single 1000
      DisplayText: Расстояние между буями
    StartDistanceToTarget: 
      Value: !System.Single 6200
      DisplayText: Расстояние до цели
    MPC_RANGE: 
      Value: !System.Single 6
      DisplayText: Дальность обнаружения МПЦ
    RocketDistance: 
      Value: !System.Single 500
      DisplayText: Расстояние между ракетами при ударе
    RocketNum: 
      Value: !System.Single 3
      DisplayText: Количество ракет
    BuoysShootRangeDiff: 
      Value: !System.Single 0
      DisplayText: Разность дальности полета буев
    Weather: 
      Value: !System.Single 0
      DisplayText: Погода
    NumBuoys: 
      Value: !System.Single 1
      DisplayText: Количество буев
    BuoysDetectRange: 
      Value: !System.Single 5000
      DisplayText: Дальность обнаружения буями
    BuoyBreakStartAltitude: 
      Value: !System.Single 50
      DisplayText: Высота начала торможения буя
    BuoysShootRange: 
      Value: !System.Single 5000
      DisplayText: Дальность полета буев
...
